popshootjapan/WeiWallet-iOS

Makefile

You can configure by `make boostrap` 👍

Fix make action in README.md

---

Wei/Model/TransactionContext.swift

- Added a validation condition where addresses start with 0x prefix

Check if the address starts with 0x

---

Wei/DI/ViewModelAssembly.swift
Wei/Utility/MnemonicManager.swift
Wei/View/CreateWallet/CreateWalletViewModel.swift
Wei/View/RestoreWallet/RestoreWalletViewModel.swift

- I forgot to change other place

[BUG] verify mnemonic at other place too

---

Wei/Model/Gas.swift
Wei/View/Send/SelectAmount/SelectAmountViewModel.swift
Wei/View/Send/SendConfirmation/SendConfirmationViewModel.swift

- Changed fixed gas price to 12 GWei which is safe low gas price
- Will get estimate gas price from node or server in the near future release

Change fixed GasPrice

---

Wei/View/Root/RootViewModel.swift

- Fixed presentCreateWalletViewController logic

Fix presentCreateWalletViewController logic

---

Wei/Model/Gas.swift

Forgot to convert gwei to wei

---

Wei.xcodeproj/project.pbxproj
Wei/Info.plist

- Added URL scheme implementation

Add URL Scheme

---

Wei/DI/UtilityAssembly.swift
Wei/Utility/BalanceStore.swift

Cache ether balance

---

Wei/View/Send/SelectAmount/BalanceAccessoryView.swift
Wei/View/Send/SelectAmount/BalanceAccessoryView.xib
Wei/View/Send/SelectAmount/SelectAmountViewController.swift
Wei/View/Send/SelectAmount/SelectAmountViewModel.swift

- display balance and available balance separately

Update select amount view controller design

---

Wei.xcodeproj/project.pbxproj
Wei/DI/UtilityAssembly.swift
Wei/Info.plist
Wei/Model/Locale.swift
Wei/Model/UserAgent.swift
Wei/Utility/BalanceStore.swift
Wei/Utility/MnemonicManager.swift
Wei/View/Send/SelectAmount/BalanceAccessoryView.swift
Wei/View/Send/SelectAmount/BalanceAccessoryView.xib
Wei/View/Send/SelectAmount/SelectAmountViewController.swift
Wei/View/Send/SelectAmount/SelectAmountViewModel.swift

- Release 1.1.0
- Caches responses
- Store pending transactions locally
- Fix available sending amount

Release 1.1.0

---

Wei.xcodeproj/project.pbxproj
Wei/Info.plist
Wei/View/CreateWallet/CreateWalletViewController.storyboard
Wei/View/CreateWallet/CreateWalletViewController.swift
WeiTests/Info.plist

Release 1.1.0 rejected

---

Wei.xcodeproj/project.pbxproj
Wei/DI/UtilityAssembly.swift
Wei/DI/ViewModelAssembly.swift
Wei/Extension/EthereumKit+Extension.swift
Wei/Model/Currency.swift
Wei/Model/Locale.swift
Wei/Utility/ApplicationStore.swift
Wei/Utility/BalanceStore.swift
Wei/Utility/CurrencyManager.swift
Wei/Utility/Formatter.swift
Wei/Utility/RateStore.swift
Wei/Utility/UserDefaultsStore.swift
Wei/View/MyWallet/MyWallet/MyWalletViewController.storyboard
Wei/View/MyWallet/MyWallet/MyWalletViewController.swift
Wei/View/MyWallet/MyWallet/MyWalletViewModel.swift

- Manage user's currency information in CurrencyManager
- Support USD in RateStore
- Support USD in BalanceStore
- Support USD in MyWallet

Implement CurrencyManager and support USD in MyWallet

---

WeiTests/KeychainStoreTests.swift

- Store keychain data to properties temporarily and put them back after testing

Prevent keychain data from being deleted when running tests

---

Wei.xcodeproj/project.pbxproj
WeiTests/CurrencyManagerTests.swift
WeiTests/MockApplicationStoreTests.swift
WeiTests/Utility/MockApplicationStore.swift

- Add MockApplicationContext
- Add MockApplicationContextTests
- Add CurrencyManagerTests

Add CurrencyManager tests

---

Wei.xcodeproj/project.pbxproj
WeiTests/SelectAddressByQRViewModelTests.swift

Add tests for SelectAddressByQRViewModel

---

Wei.xcodeproj/project.pbxproj
WeiTests/MockRateRepositoryTests.swift
WeiTests/TestUtility/MockRateRepository.swift

Add MockRateRepositoryTests

---

Wei/R.generated.swift
Wei/View/Backup/Base.lproj/BackupViewController.storyboard
Wei/View/Backup/en.lproj/BackupViewController.strings
Wei/View/Send/SelectAddressByPaste/Base.lproj/SelectAddressByPasteViewController.storyboard
Wei/View/Send/SelectAmount/Base.lproj/BalanceAccessoryView.xib
Wei/View/Send/SendConfirmation/Base.lproj/SendConfirmationViewController.storyboard
Wei/View/Send/SendConfirmation/en.lproj/SendConfirmationViewController.strings
Wei/View/SuggestBackup/Base.lproj/SuggestBackupViewController.storyboard

Fix layout

---

Wei/R.generated.swift
Wei/View/Tutorial/TutorialTopView.swift
Wei/en.lproj/Localizable.strings
Wei/ja.lproj/Localizable.strings

Localize tutorial

---

Cartfile.resolved
Wei.xcodeproj/project.pbxproj
Wei/DI/UIViewController.Container+Extension.swift
Wei/DI/UtilityAssembly.swift
Wei/DI/ViewControllerAssembly.swift
Wei/DI/ViewModelAssembly.swift
Wei/Extension/EthereumKit+Extension.swift
Wei/Model/Network.swift
Wei/R.generated.swift
Wei/Utility/ApplicationStore.swift
Wei/Utility/GethRepository.swift
Wei/Utility/UserDefaultsStore.swift
Wei/Utility/WalletManager.swift
Wei/View/NetworkSetting/NetworkSettingViewCell.swift
Wei/View/NetworkSetting/NetworkSettingViewController.storyboard
Wei/View/NetworkSetting/NetworkSettingViewController.swift
Wei/View/NetworkSetting/NetworkSettingViewModel.swift
Wei/View/Root/RootViewController.swift
Wei/View/Setting/Base.lproj/SettingViewController.storyboard
Wei/View/Setting/SettingViewController.swift
Wei/View/Setting/en.lproj/SettingViewController.strings
Wei/View/Setting/ja.lproj/SettingViewController.strings
Wei/en.lproj/Localizable.strings
Wei/ja.lproj/Localizable.strings

- Add feature to switch network for dev use

Switch network feature 

---

.gitignore
Cartfile.resolved
Wei.xcodeproj/project.pbxproj
Wei/DI/UIViewController.Container+Extension.swift
Wei/DI/UtilityAssembly.swift
Wei/DI/ViewControllerAssembly.swift
Wei/DI/ViewModelAssembly.swift
Wei/Extension/EthereumKit+Extension.swift
Wei/Info.plist
Wei/Model/Network.swift
Wei/R.generated.swift
Wei/Utility/ApplicationStore.swift
Wei/Utility/GethRepository.swift
Wei/Utility/UserDefaultsStore.swift
Wei/Utility/WalletManager.swift
Wei/View/NetworkSetting/NetworkSettingViewCell.swift
Wei/View/NetworkSetting/NetworkSettingViewController.storyboard
Wei/View/NetworkSetting/NetworkSettingViewController.swift
Wei/View/NetworkSetting/NetworkSettingViewModel.swift
Wei/View/Root/RootViewController.swift
Wei/View/Setting/Base.lproj/SettingViewController.storyboard
Wei/View/Setting/SettingViewController.swift
Wei/View/Setting/en.lproj/SettingViewController.strings
Wei/View/Setting/ja.lproj/SettingViewController.strings
Wei/en.lproj/Localizable.strings
Wei/ja.lproj/Localizable.strings
WeiTests/Helper/MockApplicationStore.swift
WeiTests/Info.plist

Release 1.2.0 resubmit

---

Wei.xcodeproj/project.pbxproj
Wei/Info.plist
WeiTests/Info.plist

Release 1.2.1

---

Wei/Utility/DeepLinkAction.swift
Wei/Utility/DeepLinkActionHandler.swift

Refactoring deeplink

---

Wei/DI/UIViewController.Container+Extension.swift
Wei/DI/ViewControllerAssembly.swift
Wei/DI/ViewModelAssembly.swift
Wei/Utility/DeepLinkActionHandler.swift
Wei/View/SignTransaction/SignTransactionViewController.swift
Wei/View/SignTransaction/SignTransactionViewModel.swift

support broadcast action via SDK

---

Wei/AppDelegate.swift
Wei/Utility/DeepLinkActionHandler.swift

Handing SDK action for handling a signing message feature

---

Wei/R.generated.swift
Wei/View/Receive/Base.lproj/ReceiveViewController.storyboard
Wei/View/Receive/ReceiveViewController.swift
Wei/View/Receive/ReceiveViewModel.swift
Wei/en.lproj/Localizable.strings
Wei/ja.lproj/Localizable.strings

Share QR code

---

Wei/R.generated.swift
Wei/View/MyWallet/MyWallet/MyWalletViewController.swift
Wei/View/MyWallet/MyWallet/MyWalletViewModel.swift
Wei/en.lproj/Localizable.strings
Wei/ja.lproj/Localizable.strings

Show which network you are using for devs

---

Wei.xcodeproj/project.pbxproj
Wei/DI/UIViewController.Container+Extension.swift
Wei/DI/ViewControllerAssembly.swift
Wei/DI/ViewModelAssembly.swift
Wei/Model/Gas.swift
Wei/R.generated.swift
Wei/Utility/ApplicationStore.swift
Wei/Utility/UserDefaultsStore.swift
Wei/View/GasSetting/GasSettingViewController.storyboard
Wei/View/GasSetting/GasSettingViewController.swift
Wei/View/GasSetting/GasSettingViewModel.swift
Wei/View/Send/SelectAmount/SelectAmountViewModel.swift
Wei/View/Send/SendConfirmation/SendConfirmationViewModel.swift
Wei/View/Setting/Base.lproj/SettingViewController.storyboard
Wei/View/Setting/SettingViewController.swift
Wei/View/SignTransaction/SignTransactionViewModel.swift

Feature to adjust gas price

---

Wei/R.generated.swift
Wei/View/Home/Base.lproj/HomeViewController.storyboard
Wei/View/Home/HomeViewController.swift
Wei/View/Home/HomeViewModel.swift
Wei/View/MyWallet/LatestTransactionList/Base.lproj/LatestTransactionListViewController.storyboard
Wei/View/MyWallet/MyWallet/Base.lproj/MyWalletViewController.storyboard
Wei/View/MyWallet/MyWallet/MyWalletViewController.swift

New layout of wallet tab

---

Podfile
Podfile.lock
Wei.xcodeproj/project.pbxproj
Wei.xcodeproj/xcshareddata/xcschemes/Wei.xcscheme

Install Web3Provider
